---
site:
  title: "Serve LLMs on Intel Xeon CPUs"
  url: https://github.com/rhpds/showroom-intel-llm-cpu-serving
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/latest/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui

runtime:
  fetch: true

output:
  dir: ./www
